### PR TITLE
Add ToField and FromField instances for Natural

### LINKED ISSUE #141: toField instance for Natural
From `Numeric.Natural`

### PR DESCRIPTION
**Pull request by expipiplus1**
Closes #141

### CODE REVIEW

**Comment by hvr** [comment]
@expipiplus1 have you noticed the testsuite-failures?

**Comment by expipiplus1** [comment]
I had not noticed! Looks like the nats package needs to be added as a dependency for ghc < 7.10

**Comment by hvr** [comment]
@expipiplus1 yeah, something akin to `if impl(ghc < 7.10); build-depends: nats >= 1 && < 1.2` should suffice.

Can you also look at https://github.com/hvr/cassava/pull/144 as an example of other things to be done when adding an instance?

**Comment by expipiplus1** [comment]
@hvr done

**Comment by hvr** [comment]
thanks!

**Pull request merged**
