### PR TITLE
Don't unnecessarily quote fields with spaces.

### PR DESCRIPTION
**Pull request by luke-clifton**
Addresses #118 

I have changed `QuoteMinimal` to not quote on spaces.

I have added a `QuoteConservative` which behaves like the old `QuoteMinimal`.

The default encoding options now specifies `QuoteConservative` in an attempt to minimize any potential breakage.

### CODE REVIEW

**Comment by tfausak** [comment]
I would love to have this. It surprised me that the default encoding mode puts quotes around strings with spaces in them. I'm annoyed by the lack of a way to work around this problem. 

This is especially weird considering [the first thing in the README](https://github.com/hvr/cassava/blob/a983873fb350b33ef8daab94b629741623d3c9a8/README.md#usage-example) is a CSV that has a string with spaces in it that isn't wrapped in quotes.

> Here's the two second crash course in using the library. Given a CSV file with this content:
>
>     John Doe,50000
>     Jane Doe,60000

**Comment by tfausak** [comment]
This would also fix #86, which is a duplicate of #118.

**Comment by hvr** [comment]
@luke-clifton Is there any actual demand for `QuoteConservative` ? If we introduce a new constructor (and I'm considering adding the non-numerical one mentioned in the comment in #86), we've got to signal a major version bump anyway, which is basically a very loud "heads up" signal to maintainers to review the API for semantic breaking changes. At which point I'd rather change the default to the less arbitrary rfc4180-minimal mode.

**Comment by tibbe** [comment]
IIRC I had the default match the RFC (although I know that lots of software doesn't follow it closely).

**Comment by luke-clifton** [comment]
I''m fine with dropping it.

**Comment by hvr** [comment]
resolved by 2fd71dd

**Pull request closed without merging**
