### PR TITLE
Only incrementally include the header if requested

### LINKED ISSUE #136: encodeDefaultOrderedByNameWith should respect encIncludeHeader
The inclusion of the header emitted by `encodeDefaultOrderedByNameWith` should be based upon the value of  `encIncludeHeader` from the provided `EncodeOptions`.

### PR DESCRIPTION
**Pull request by ivan-m**
Closes #136

### CODE REVIEW

**Comment by hvr** [comment]
Thanks!

**Comment by ivan-m** [comment]
Do you have an idea about when this will be available in a release?

I have a library I'm about ready to release that's currently missing the name-based encoding support because of this issue, but if you're going to make a release soon I might hold up and wait so it can be feature complete.

**Comment by hvr** [comment]
@ivan-m soon-ish; it would help a lot if you could give the current state in `master` a test-run and let me know if this release works for you.

**Comment by ivan-m** [comment]
Well, using this (rather than converting one row at a time using `Data.Csv.encodeByNameWith (opts { encIncludeHeader = False } . (:[])` seems to work and passes my QC-based test suite.

**Comment by hvr** [comment]
@ivan-m thanks!

**Pull request merged**
